export interface ResponseType {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date;
  code: string;
  name: string;
  is_active: boolean;
}
// Generated by https://quicktype.io

export interface AllCareCentersType {
  id: number;
  created_at: string;
  updated_at: string;
  organization_name: string;
  logo_id: number;
  logo: Logo;
  is_active: boolean;
  contact: Contact;
  email: string;
  payment: Payment;
  created_user_id: number;
  is_accreditation: boolean;
  status: number;
  approved_user_id: null;
  donations: Donations;
  document: null;
  time_schedules: null;
  accreditations: null;
}

export interface Contact {
  first_name: string;
  last_name: string;
  position: string;
  phone: string;
}

export interface Donations {
  description: string;
  longitude: string;
  latitude: string;
}

export interface Logo {
  id: number;
  created_at: string;
  updated_at: string;
  file_name: string;
  original_name: string;
  physical_path: string;
  extention: string;
  file_size: number;
}

export interface Payment {
  bank_name: string;
  account_number: string;
  receiver_name: string;
}

// Generated by https://quicktype.io

export interface AllElderlyNoteType {
  id: number;
  created_at: string;
  updated_at: string;
  elderly_id: number;
  care_center_id: number;
  date: string;
  name: string;
  description: string;
  care_center_elderly_note_files: null;
  created_employee_id: number;
  modified_employee_id?: number;
}
