import { Base } from 'types';

export interface CareListProps {
  image: any[];
  name: string;
  brand: string;
}

export enum FilterServecingline {
  Waiting = 4,
  Serving = 6,
}

export interface FilterServicingButton {
  value: FilterServecingline;
  label: string;
}

export enum FilterDevelopmentline {
  active = 0,
  history = 1,
}

export interface FilterDevelopmentButton {
  value: FilterDevelopmentline;
  label: string;
}

export enum FilterDocumentline {
  contract = 0,
  client_doc = 1,
  health_doc = 2,
}

export interface FilterDocumentButton {
  value: FilterDocumentline;
  label: string;
}

export interface CareinformationService extends Base {
  first_name: string;
  last_name?: string;
  rd: string;
  gender?: number;
  age: number;
  is_disability?: boolean;
  education: string;
  occupation?: string;
  pension: number;
  marriage: string;
  family_count: number;
  children_count: number;
  main_address?: string;
  reason?: string;
  laboratory_test: any;
  // price_range?: number;
  // tags?: string[];
  // discount?: number;
  // discount_start_date?: Date;
  // discoutn_end_date?: Date;
  // is_active: boolean;
  // verified_at?: Date;
  // sponsored_at?: Date;
  // commission_event?: number;
  // commission_coupon?: number;
  // commission_product?: number;
  // commission_start_date?: Date;
  // account_number?: string;
  // account_bank?: string;
  // account_holder?: string;
  // total_click: number;
  // subscription_price?: number;
  // subscription_end_date?: Date;
  // subscription_name?: string;
  // is_event: boolean;
  // is_product: boolean;
  // is_coupon: boolean;
  // is_auto_sponsored: boolean;
  // review_count: number;
}

// Generated by https://quicktype.io
export interface ElderlyList {
  id: number;
  created_at: string;
  updated_at: string;
  elderly_id: number;
  elderly: Elderly;
  care_center_id: number;
  social_worker_elderly_id: number;
  status: number;
  three_way_contract: null;
  social_worker_elderly: any;
  jewelry_registry: null;
  situational: null;
  is_see_internal_regulations: boolean;
  received_employees: null;
  received_document_items: string;
  received_date: string;
  delivered_person: DeliveredPerson;
  created_employee_id: number;
}

export interface StatusCount {
  status: number
  count: number
}

export interface Profile {
  id: number;
  created_at: string;
  updated_at: string;
  file_name: string;
  original_name: string;
  physical_path: string;
  extention: string;
  file_size: number;
  created_user_id: number;
}

export interface DeliveredPerson {
  city_id: number;
  district_id: number;
  khoroo_id: number;
  first_name: string;
  position: string;
  phone_number: string;
}

export interface Elderly {
  id: number;
  created_at: string;
  updated_at: string;
  profile_id: number;
  family_name: string;
  first_name: string;
  last_name: string;
  profile: Profile;
  rd: string;
  gender: number;
  age: number;
  birth_date: string;
  is_disability: boolean;
  disability_desc: string;
  education: string;
  reason: string;
  marriage: string;
  family_count: number;
  children_count: number;
  address: null;
  situational: null;
  definition_governor: null;
  created_user_id: number;
}

// Generated by https://quicktype.io

// export interface HealthConditionType {
//   id: number;
//   created_at: string;
//   updated_at: string;
//   elderly_id: number;
//   care_center_id: number;
//   service_name: string;
//   description: string;
//   created_employee_id: number;
// }

// Generated by https://quicktype.io

export interface HealthConditionType {
  id: number;
  created_at: string;
  updated_at: string;
  elderly_id: number;
  care_center_id: number;
  service_name: string;
  description: string;
  created_employee_id: number;
  created_employee: CreatedEmployee;
}

export interface CreatedEmployee {
  id: number;
  created_at: string;
  updated_at: string;
  profile_id: number;
  profile: Profile;
  family_name: string;
  rd: string;
  birth_date: string;
  gender: number;
  is_disability: boolean;
  salary: number;
  first_name: string;
  last_name: string;
  email: string;
  is_active: boolean;
  phone: string;
  position: string;
  care_center_id: number;
  total_worked_year: number;
  worker_year: number;
}

export interface Profile {
  id: number;
  created_at: string;
  updated_at: string;
  file_name: string;
  original_name: string;
  physical_path: string;
  extention: string;
  file_size: number;
}

// Generated by https://quicktype.io

export interface NoteListType {
  id: number;
  created_at: string;
  updated_at: string;
  elderly_id: number;
  care_center_id: number;
  date: string;
  description: string;
  care_center_elderly_note_files: CareCenterElderlyNoteFile[];
  created_employee_id: number;
  modified_employee_id?: number;
}

export interface CareCenterElderlyNoteFile {
  id: number;
  created_at: string;
  updated_at: string;
  file_name: string;
  original_name: string;
  physical_path: string;
  extention: Extention;
  file_size: number;
}

export enum Extention {
  PNG = 'png',
}

// Generated by https://quicktype.io

export interface ElderlyDPlist {
  id: number;
  created_at: string;
  updated_at: string;
  care_center_id: number;
  structure: string;
  purpose: string;
  activity: string;
  duration: number;
  created_employee_id: number;
  modified_employee_id?: number;
  elderly_dps: ElderlyDP[];
}

export interface ElderlyDP {
  id: number;
  created_at: string;
  updated_at: string;
  elderly_id: number;
  care_center_id: number;
  plan_id: number;
  description: string;
  deadline: string;
  count: number;
  frequency: number;
  created_employee_id: number;
  created_employee: CreatedEmployee;
  dtls: any[];
}

export interface CreatedEmployee {
  id: number;
  created_at: string;
  updated_at: string;
  profile_id: number;
  profile: Profile;
  family_name: string;
  rd: string;
  birth_date: string;
  gender: number;
  is_disability: boolean;
  salary: number;
  first_name: string;
  last_name: string;
  email: string;
  is_active: boolean;
  phone: string;
  position: string;
  care_center_id: number;
  total_worked_year: number;
  worker_year: number;
}
export interface Profile {
  id: number;
  created_at: string;
  updated_at: string;
  file_name: string;
  original_name: string;
  physical_path: string;
  extention: string;
  file_size: number;
}
